### PR TITLE
sdl1_video_demo.c: Fix resize for when the mouse is hold and not moving

### PR DESCRIPTION
**Pull request by hartwork**
CC @kaixiong

### CODE REVIEW

**Comment by kaixiong** [comment]
@hartwork, nice, this works for me. The video does flicker a bit as the rendering code adapts to the resize.

I had a similar idea for debouncing resize events but using a timer instead. When a resize event is received, any further resize events in the debounce period (say 0.5 seconds) will be ignored. When the period expires, the content resize is performed.

**Comment by kaixiong** [comment]
Just to add, I've done this for slow content resizes for web apps that contain large data grids. It's fairly straightforward to queue up timed functions in JS. It's a bit more work with C/C++ unless you're using a library like Glib which has a built in main/event loop.

**Comment by hartwork** [comment]
> @hartwork, nice, this works for me. The video does flicker a bit as the rendering code adapts to the resize.
> 
> I had a similar idea for debouncing resize events but using a timer instead.

@kaixiong that was my first impulse, too. The approach in here is inspired by something I saw in SDL 1 library code.

> When a resize event is received, any further resize events in the debounce period (say 0.5 seconds) will be ignored. When the period expires, the content resize is performed.
>
> Just to add, I've done this for slow content resizes for web apps that contain large data grids. It's fairly straightforward to queue up timed functions in JS. It's a bit more work with C/C++ unless you're using a library like Glib which has a built in main/event loop.

I have a demo of debouncing in branch `fix-sdl1-resize-behavior-debounce` now, see https://github.com/hartwork/sdl_video_demo/compare/master..fix-sdl1-resize-behavior-debounce for the diff. I'm not sure I like it better. It seems to need a clock with a higher resolution and the complexity is a lot higher. I think I prefer faster with flicker over the delay, personally, at least in SDL context. What do you think?

**Comment by hartwork** [comment]
@kaixiong PS: Note that I have chosen to not accumulate resize requests beyond the time limit, so f you keep resizing for minutes, it will not take a minute to do the first resize. That was intended.

**Comment by kaixiong** [comment]
@hartwork The new version looks vastly better to me. I personally really dislike flickering.

The other benefit that is not apparent in this demo is that content resizes can be very slow. Some of the software visualizations in LV will crawl at large dimensions. If we apply the content resize too rapidly, it may not only flicker but also lag very badly.

**Comment by hartwork** [comment]
@kaixiong alright, let's do that then. I'll merge the alternative at (new) #10 now.

**Pull request closed without merging**
